all:
	@echo Setting up files...
	@sudo cp main.php /opt/lampp/htdocs/AdventOfCode/
	@sudo cp input.txt /opt/lampp/htdocs/AdventOfCode/
	@sudo cp test.txt /opt/lampp/htdocs/AdventOfCode/
	@echo Running...
	@google-chrome-stable localhost/AdventOfCode/main.php
	@echo Done.